<h1>Calendar</h1>
<?php
echo $this->getLayout()
    ->createBlock(\Magento\Cms\Block\Block::class)
    ->setBlockId('getlayout')
    ->toHtml();
?>
<?= $block->getChildHtml('cms_to_phtml') ?>

<!-- Example 1 -->
<input type="text" name="datepicker" id="datepicker" value="" class="datepicker">
<script>
    require(["jquery", "mage/calendar"], function($) {
        $("#datepicker").datepicker({
            showMonthAfterYear: false,
            dateFormat: 'mm/dd/yy',
            changeMonth: true,
            changeYear: true,

            yearRange: '2000:2024',

        })
    });
</script>

<!-- Example 2 -->
<!-- <input type="text" name="datetimepicker" id="datetimepicker" value="" class="datetimepicker">
<script>
    require([

        'jquery',


        'mage/calendar'
    ], function($) {

        $('#datetimepicker').datetimepicker({
            dateFormat: 'mm/dd/yy',
            timeFormat: 'HH:mm:ss',
            changeMonth: true,
            changeYear: true,

            showsTime: true

        });
    });
</script> -->

<!-- Example 3 -->
<!-- <div class="field required" id="daterange">
    <label for="from" class="label">
        <span>From date</span>
    </label>
    <div class="control">

        <input class="input-text required-entry" type="text" id="from-date" name="from-date" style="width: 500px" />
    </div>
    <label for="to" class="label">

        <span>To date</span>
    </label>
    <div class="control">

        <input class="input-text required-entry" type="text" id="to-date" name="to-date" style="width: 500px" />
    </div>
</div>

<script>
    require([

        'jquery',
        'mage/calendar'
    ], function($) {
        $('#daterange').dateRange({
            buttonText: 'Choose Date',
            from: {

                id: 'from-date'
            },
            to: {

                id: 'to-date'

            }
        });
    });
</script> -->